site_name: DNS documentation
site_url: https://dnobrega.github.io/DNS/

#Repository
repo_name: dnobrega/DNS
repo_url: https://github.com/dnobrega/DNS
edit_uri: ""

nav:
  - About me: index.md
  - Bifrost: bifrost.md

theme:
  name: 'material'
  palette:
    primary: 'deep orange'
    secondary: 'deep orange'
    accent: 'teal'
  favicon: 'images/favicon_flare.png'
#  feature:
#    tabs: true

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 Daniel Nobrega Siverio'
# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/dnobrega'
# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true