##################################################################

site_name: DNS
site_url: https://dnobrega.github.io/DNS/
site_author: Daniel Nobrega-Siverio
site_description: "Documentation about useful software packages, 
                   code, telescopes and satellites."
copyright: 'Copyright &copy; 2019 - 2022 Daniel Nobrega Siverio'
repo_name: dnobrega/DNS
repo_url: https://github.com/dnobrega/DNS
edit_uri: ""

##################################################################

theme:
    name: mkdocs
    nav_style: dark
    navigation_depth: 3
    highlightjs: true

##################################################################

nav:
  - '': index.md
  - 'Software':
    - Mac OS: macos.md
    - IDL: idl.md
    - Python: python.md
    - Bifrost: bifrost.md
  - 'Observations':
    - ALMA: alma.md  
    - IRIS: iris.md
    - SOLO: solo.md
    - SDO: sdo.md
    - SST: sst.md


##################################################################

# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite:
      guess_lang: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight  
  - pymdownx.arithmatex
  - pymdownx.tilde
  - fontawesome_markdown

##################################################################


