site_name: DNS documentation
site_url: https://dnobrega.github.io/DNS/
site_author: Daniel Nobrega-Siverio
site_description: "Documentation about useful software packages, code, telescopes and satellites."
copyright: 'Copyright &copy; 2019 - 2022 Daniel Nobrega Siverio'

#Repository
repo_name: dnobrega/DNS
repo_url: https://github.com/dnobrega/DNS
edit_uri: ""

nav:
  - Introduction: index.md
  - Mac OS: macos.md
  - Terminal: terminal.md
  - Python: python.md  
  - Bifrost: bifrost.md
  - IDL and SSWIDL: sswidl.md
  - IDL: idl.md
  - DNSPRO: dns.md
  - SST: SST.md
  - IRIS: IRIS.md
  - SOLO: SOLO.md
#  - SDO: SDO.md
#  - ALMA: ALMA.md  
#  - About me: about.md

theme:
  name: null
  custom_dir: 'cinder'
  colorscheme: github
  highlightjs: true
  hljs_languages:
    - yaml

# Customization
#extra:
#  manifest: 'manifest.webmanifest'
#  social:
#    - type: 'github'
#      link: 'https://github.com/dnobrega'
# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true
#  - pymdownx.details
#  - pymdownx.superfences
#  - pymdownx.highlight
#  - codehilite:
#      guess_lang: false

