##################################################################

site_name: DNS
site_url: https://dnobrega.github.io/DNS/
site_author: Daniel Nobrega-Siverio
site_description: "Documentation about useful software packages, 
                   code, telescopes and satellites."
copyright: 'Copyright &copy; 2019 - 2022 Daniel Nobrega Siverio'
repo_name: dnobrega/DNS
repo_url: https://github.com/dnobrega/DNS
edit_uri: ""

##################################################################

theme:
    name: mkdocs
    nav_style: dark
    navigation_depth: 3
    highlightjs: true

##################################################################

nav:
  - '': index.md
  - Mac OS: macos.md
  - Terminal: terminal.md
  - Bifrost: bifrost.md
  - 'Programming languages':
    - IDL: idl.md
    - Python: python.md
  - 'Observations':
    - SST: SST.md
    - IRIS: IRIS.md
    - SOLO: SOLO.md
    - SDO: SDO.md
    - ALMA: ALMA.md  
#  - About me: about.md

##################################################################

# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite:
      guess_lang: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight  
  - pymdownx.arithmatex
  - pymdownx.tilde
  - fontawesome_markdown

##################################################################


