site_name: DNS documentation
site_url: https://dnobrega.github.io/DNS/

#Repository
repo_name: dnobrega/DNS
repo_url: https://github.com/dnobrega/DNS
edit_uri: ""

nav:
  - INTRODUCTION: index.md
  - MAC OS: macos.md
  - PYTHON: python.md  
  - BIFROST: bifrost.md
  - SSWIDL: sswidl.md
  - IDL: idl.md
  - DNS: dns.md
  - SST: SST.md
  - IRIS: IRIS.md
  - SDO: SDO.md
  - ALMA: ALMA.md  
  - UNIX: unix.md
  - ABOUT ME: about.md

theme:
  name: 'readthedocs'
  favicon: 'images/dns.png'

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 Daniel Nobrega Siverio'
# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/dnobrega'
# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
