#!/bin/bash
#------------------------------------------------------
# Script to add 4 zeros to all the files ending in $1
#------------------------------------------------------
rename -e 's/\d+/sprintf("%04d",$&)/e' -- *.$1
