#!/bin/bash
weight=`du -hm $1 | awk '{print $1}'`
hi1=`gdate +%s.%N`
cp -p $1 $2
hi2=`gdate +%s.%N`
ttime=`echo $hi1 $hi2 | awk '{print $2-$1}'`
velocity=`awk "BEGIN {print 8*$weight/$ttime}"`
echo "Transfer velocity is" $velocity "Mbps"
