#!/bin/bash
curl -s $1 | grep SAAI | awk '{print $2}' | sed -e 's/\(:..\).*/\1/' > saai.txt
curl -s $1 | grep SAAO | awk '{print $2}' | sed 's/\(:..\).*/\1 IRIS in SAA <br\>/'  > saao.txt
paste -d "~" saai.txt saao.txt | sed 's/~/ - /' | pbcopy -selection c
rm saai.txt
rm saao.txt